base_frame_id: base_link
beam_skip_distance: 0.5
beam_skip_threshold: 0.3
do_beamskip: false
first_map_only: false
global_frame_id: map
gui_publish_rate: 10.0
initial_cov_aa: 2.5307478396095155e-05
initial_cov_xx: 0.0005703408219208794
initial_cov_yy: 0.0003184986423164504
initial_pose_a: 0
initial_pose_x: 0
initial_pose_y: 0
kld_err: 0.04
kld_z: 0.99 
laser_lambda_short: 0.3
laser_likelihood_max_dist: 2.0
laser_max_beams: 250
laser_max_range: 8.0
laser_min_range: -1.0
laser_model_type: likelihood_field
laser_sigma_hit: 0.2
laser_z_hit: 0.5
laser_z_max: 0.05
laser_z_rand: 0.5
laser_z_short: 0.05
max_particles: 1000
min_particles: 100
odom_alpha1: 0.1
odom_alpha2: 0.2
odom_alpha3: 0.2
odom_alpha4: 0.3
odom_alpha5: 0.3
odom_frame_id: odom
odom_model_type: omni-corrected
recovery_alpha_fast: 0.1
recovery_alpha_slow: 0.01
resample_interval: 1
restore_defaults: false
save_pose_rate: 0.5
tf_broadcast: false
transform_tolerance: 0.2
update_min_a: 0.0
update_min_d: 0.0
use_map_topic: true
